### ISSUE TITLE
Rephrase last question of chapter 1

### ISSUE THREAD

**Issue by rogererens** [timothypratley/enterprise-clojure-training#16]
The last question "How many digits are in 5 factorial?" should have the answer 3.
One can get that with "(count (str (* 5 4 3 2 1))" but the count and str functions have not been introduced yet. So I think the question might better be rephrased to something like "How much is 5 factorial?"

**Comment by timothypratley** [comment]
@rogererens thank you very much for raising this issue. I have implemented your recommendation.
